### PR TITLE
Add deprecation notice to V1 API

### PR DESCRIPTION
**Pull request by rrdelaney**

### CODE REVIEW

**Comment by sirbrokealot** [comment]
I'm currently using the /api/req endpoint to fetch details for some commanders, but I've noticed that some of the endpoints are now deprecated, hence the message: "This API is deprecated. If still in use, please contact EDHTop16 admins."

For reference, I was/am using post on https://edhtop16.com/api/req with a json body containing
"commander", 
"tourney_filter__size__gte",
"tourney_filter__dateCreated__gte",
"standing__lte",
"wins__gte"
"winRate__gte": 
    
I've noticed that this endpoint now requires an x-deprecation-acknowledgement header. While I understand the purpose of acknowledging deprecated features, I'm struggling to find any updated or v2 versions of this endpoint. Specifically, I see that the /api/req endpoint for commanders is still implemented in legacy_api.ts on the client side, which leads me to wonder if there is a newer recommended endpoint I should be using. Maybe the endpoints are just no longer needed by the ui i thought. 
Could you please provide some brief guidance on where I might find updated endpoints or documentation regarding these changes?

**Comment by JasonQiu21** [comment]
I'd recommend using our graphql endpoint now https://edhtop16.com/api/graphql

**Comment by sirbrokealot** [comment]
Thank you @JasonQiu21 @rrdelaney for your replies.

I adapted my code and routines to utilize the new graphql endpoint.

**Comment by rrdelaney** [comment]
> Thank you @JasonQiu21 @rrdelaney for your replies.
> 
> I adapted my code and routines to utilize the new graphql endpoint.

That's great! Could you share your GraphQL query? Just curious and also want to make sure we don't break you.

**Pull request merged**
